  - name: "Add a label to a managed cluster"
    kubernetes.core.k8s:
      state: "{{ state }}"
      #host: "{{ cluster_proxy.cluster_url }}"
      validate_certs: no
      #api_key: "{{ managed_serviceaccount.token }}"
      api_version: cluster.open-cluster-management.io/v1
      kind: ManagedCluster
      name: "{{ ansible_host }}"
      definition:
        metadata:
          labels:
            '{{ applied_label }}'
