- name: "Create kubeconfig directory if does not exist"
  file:
    path: ../kubeconfig
    state: directory
- name: "Generate Kubeconfig file"
  template:
    src: ../roles/k8s-cluster-access/templates/kubeconfig.yml
    dest: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
#- name: "Upload kubeconfig to deploy host"
#  ansible.builtin.uri:
#    url: "{{ upload_url }}"
#    method: POST
#    src: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
- name: "Upload kubeconfig to deploy host"
  ansible.builtin.uri:
    url: "{{ upload_url }}"
    method: POST
    body_format: form-multipart
    body:
      kubeconfig:
        filename: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
