- name: "Create kubeconfig directory if does not exist"
  file:
    path: ../kubeconfig
    state: directory
- name: "Generate Kubeconfig file"
  template:
    src: ../roles/k8s-cluster-access/templates/kubeconfig.yml
    dest: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"

- name: "Copy kubeconfig to deployhost"
  ansible.posix.synchronize:
    src: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
    dest: rsync://{{ deploy_host }}/{{ kubeconfig_path }}
    set_remote_user: {{ deploy_user }}
