- name: "Create kubeconfig directory if does not exist"
  file:
    path: ../kubeconfig
    state: directory
- name: "Generate Kubeconfig file"
  template:
    src: ../roles/k8s-cluster-access/templates/kubeconfig.yml
    dest: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
#- name: "Upload kubeconfig to deploy host"
#  ansible.builtin.uri:
#    url: "{{ upload_url }}"
#    method: POST
#    src: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
#- name: "Upload kubeconfig to deploy host"
#  ansible.builtin.uri:
#    url: "{{ upload_url }}"
#    method: POST
#    body_format: form-multipart
#    body:
#      kubeconfig:
#        filename: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"
#        #mime_type: text/plain
#        mime_type: application/octet-stream
- name: "Upload kubeconfig to deploy host"
  ansible.builtin.command: curl -X POST -F 'kubeconfig=@"../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}"' http://10.19.33.10:8765/upload

- name: pause while I check logs
  ansible.builtin.pause:
    minutes: 2
