- name: "Create kubeconfig directory if does not exist"
  file:
    path: ../kubeconfig
    state: directory
- name: "Generate Kubeconfig file"
  template:
    src: ../roles/k8s-cluster-access/templates/kubeconfig.yml
    dest: "../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}.yaml"
- name: "Upload kubeconfig to deploy host"
  ansible.builtin.command: curl -X POST -F 'kubeconfig=@"../kubeconfig/{{ hostvars[inventory_hostname].cluster_name }}.yaml"' http://10.19.33.10:8765/upload
