- name: "Manage Clusters"
  #hosts: "{{ target_hosts }}"
  hosts: aap-ready
  connection: local
  gather_facts: false
  tasks:
    - block: 
        - debug: var=applied_label
        - include_role: 
            name: ../roles/label-cluster
          vars:
            state: "patched"
            applied_label: "{{ applied_label }}"
